config/routes.rb
Rails.application.routes.draw do
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts,     only: [:new, :create, :index]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    
    before_create :remember
    
    has_secure_password
    has_many :posts


    private
        def remember
            self.remember_token = SecureRandom.urlsafe_base64
            self.remember_digest = Digest::SHA1.hexdigest(remember_token)
            # update_attribute(:remember_digest, Digest::SHA1.hexdigest(remember_token))
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    # def current_user
    #     if (user_id = session[:user_id])
    #       @current_user ||= User.find_by(id: user_id)
    #     elsif user_id = cookies.signed[:user_id]
    #       user = User.find_by(id: user_id)
    #       if (user && Digest::SHA1.hexdigest(cookies[:remember_token]) == user.remember_digest)
    #         @current_user = user
    #       end
    #     end
    #   end

    def logged_in?
        !current_user.nil?
    end

    private
 
  def require_login
    unless logged_in?
      flash[:warning] = "You must be logged in to access this section"
      redirect_to login_url 
    end
  end

    def sign_out
        session.delete(:user_id)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
        @current_user = nil
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login,   only: [:new, :create]


  # GET /posts
  # GET /posts.json
  def index
    @user = current_user
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # p current_user
    # @post = Post.new(post_params)
    # @post.user_id = current_user.id
    @post = current_user.post.build(post_params)

    
    if @post.save
      #redirect_to action: "index"
      redirect_to({:action => :index}, {flash: {:success => 'Post published successfully'}})
    else
      flash.now[:danger] = 'Something went wrong.'
    end
    
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to posts_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    sign_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light bg-light justify-content-between">
  <%= link_to "Members Only", root_path, class: 'justify-content-start navbar-brand' %>
  
  <% if @user %>
                  <button class="btn btn-danger"><%= link_to "Log out", logout_path, method: :delete, class: 'white' %></button>
                  <% else %>
                  <button class="btn btn-info"><%= link_to "Log in", login_path, class: 'white' %></button>
              <% end %>
</nav>
  <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="actions mt-2">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="d-flex justify-content-between">
<button type="button" class="btn btn-primary"><%= link_to 'New Post', new_post_path, class: 'white' %></button>
</div>

<br>
<% if @posts.any? %>
  <div class="album text-muted">
    <div class="container">
        <div class="row">
        
          <% @posts.each do |post| %>
            <div class="card mt-2 mr-2" style="width: 18rem; height: 10rem">
              <div class="card-body">
                <h5 class="card-title"><%= post.title %></h5>
                
                
                <p class="card-text"><%= post.content %></p>
                <% if @user %>
                    <small class="card-subtitle mb-2 text-muted">Written by : <%= post.user.name %></small>
                <% end %>
              </div>
            </div>
          <% end %>
          
        </div>
    </div>
  </div>
<% else %>
  <div class="alert alert-dark" role="alert">
    There are currently no posts! 
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>